In [279]:
from fireTS.models import NARX, DirectAutoRegressor
from sklearn.neural_network import MLPRegressor
import numpy as np

# Random training data
x = np.random.randn(100, 2)
y = np.random.randn(100,2)

x = np.append(x, y, axis=1)
y1 = y[:,0]
y2 = y[:,1]

p, q , d = 3, 3, 1

# Build a non-linear autoregression model with exogenous inputs
# using MLPRegressor as the base model
mdl1 = NARX(
    MLPRegressor(random_state = 1, hidden_layer_sizes=(91), max_iter = 5000),
    auto_order=p,
    exog_order=[q, q, q, q],
    exog_delay=[d, d, d, d])
mdl1.fit(x, y1)
ypred1 = mdl1.predict(x, y1)
R2_mdl1 = mdl1.score(x, y1, method='r2')
RMSE_mdl1 = mdl1.score(x, y1, method='mse')**0.5

# # Build a general autoregression model and make multi-step prediction directly
# # using MLPRegressor as the base model
# mdl2 = DirectAutoRegressor(
#     MLPRegressor(random_state = 1, hidden_layer_sizes=(91), max_iter = 5000),
#     auto_order=p,
#     exog_order=[q, q, q, q],
#     exog_delay=[d, d, d, d],
#     pred_step =1)
# mdl2.fit(x, y)
# ypred2 = mdl2.predict(x, y)
# R2_mdl2 = mdl2.score(x, y, method='r2')
# RMSE_mdl2 = mdl2.score(x, y, method='mse')**0.5

In [280]:
mdl1

NARX(auto_order=3,
     base_estimator=MLPRegressor(activation='relu', alpha=0.0001,
                                 batch_size='auto', beta_1=0.9, beta_2=0.999,
                                 early_stopping=False, epsilon=1e-08,
                                 hidden_layer_sizes=91,
                                 learning_rate='constant',
                                 learning_rate_init=0.001, max_fun=15000,
                                 max_iter=5000, momentum=0.9,
                                 n_iter_no_change=10, nesterovs_momentum=True,
                                 power_t=0.5, random_state=1, shuffle=True,
                                 solver='adam', tol=0.0001,
                                 validation_fraction=0.1, verbose=False,
                                 warm_start=False),
     exog_delay=[1, 1, 1, 1], exog_order=[3, 3, 3, 3])

In [281]:
mdl2

DirectAutoRegressor(auto_order=3,
                    base_estimator=MLPRegressor(activation='relu', alpha=0.0001,
                                                batch_size='auto', beta_1=0.9,
                                                beta_2=0.999,
                                                early_stopping=False,
                                                epsilon=1e-08,
                                                hidden_layer_sizes=91,
                                                learning_rate='constant',
                                                learning_rate_init=0.001,
                                                max_fun=15000, max_iter=5000,
                                                momentum=0.9,
                                                n_iter_no_change=10,
                                                nesterovs_momentum=True,
                                                power_t=0.5, random_state=1,
                                 

In [282]:
x[:10]

array([[ 0.69978971, -0.3170435 , -0.18682005, -0.29104796],
       [ 1.00115199, -1.18123674,  1.62297663, -0.55983616],
       [-0.39830562, -1.32406291,  1.19737577,  1.71057083],
       [ 1.02977213, -0.73189183,  0.95842269,  0.6980463 ],
       [-0.51515139, -1.50908437, -1.84032499,  0.11861452],
       [-0.08688187,  0.35297619,  1.43412061,  0.82218709],
       [-0.499579  , -0.72379622,  0.83542657,  1.16189568],
       [-0.17359627,  1.14986568,  0.09168375, -1.08440089],
       [ 1.40775766, -1.40929964,  1.57001969,  0.77863618],
       [ 0.31594556, -0.63889716,  0.13726099,  1.32205033]])

In [283]:
y1[:10]

array([-0.18682005,  1.62297663,  1.19737577,  0.95842269, -1.84032499,
        1.43412061,  0.83542657,  0.09168375,  1.57001969,  0.13726099])

In [284]:
ypred1[:10]

array([        nan,         nan,         nan,         nan, -1.71569726,
        1.37113119,  0.79244533,  0.0110503 ,  1.54820412,  0.06666719])

In [285]:
ypred2[:10]

array([        nan,         nan,         nan,         nan, -0.27151278,
       -0.01487934,  1.08358216, -0.40579806,  0.40233704, -0.69897895])

In [286]:
print("Model 1: R2 = {} | RMSE = {}".format(R2_mdl1,RMSE_mdl1))

Model 1: R2 = 0.9920100320346246 | RMSE = 0.09854837560120597


In [287]:
print("Model 2: R2 = {} | RMSE = {}".format(R2_mdl2,RMSE_mdl2))

Model 2: R2 = 0.9921207410456336 | RMSE = 0.09036532061329337
